"""E2E test: ingest multiple documents and query across them.

Verifies that retrieval ranks the correct document first when
multiple documents with distinct topics are indexed.
"""

import os

import httpx
import pytest

API_URL = os.environ.get("OPENFABLE_API_URL", "http://localhost:8000") + "/v1/api"

DOCUMENT_PHOTOSYNTHESIS = """\
# Photosynthesis

Photosynthesis is the process by which green plants convert sunlight into chemical energy.
It occurs primarily in the leaves, within organelles called chloroplasts.

## Light-Dependent Reactions

The light-dependent reactions take place in the thylakoid membranes. Chlorophyll absorbs
light energy, which is used to split water molecules into oxygen, protons, and electrons.
ATP and NADPH are produced as energy carriers.

## Calvin Cycle

The Calvin cycle occurs in the stroma of the chloroplast. It uses ATP and NADPH from the
light-dependent reactions to fix carbon dioxide into glucose. The enzyme RuBisCO catalyzes
the first step, attaching CO2 to a five-carbon sugar called RuBP.
"""

DOCUMENT_PLATE_TECTONICS = """\
# Plate Tectonics

The Earth's lithosphere is divided into several large tectonic plates that float on the
semi-fluid asthenosphere beneath them. These plates move relative to each other at rates
of a few centimeters per year.

## Types of Plate Boundaries

There are three main types of plate boundaries: divergent, convergent, and transform.
At divergent boundaries, plates move apart and new crust forms from rising magma.
At convergent boundaries, one plate subducts beneath another, forming deep ocean trenches
and volcanic arcs. Transform boundaries occur where plates slide past each other horizontally,
such as the San Andreas Fault in California.

## Earthquakes and Volcanism

Most earthquakes and volcanic eruptions occur along plate boundaries. The Ring of Fire
encircles the Pacific Ocean and accounts for approximately 75% of the world's active
volcanoes and 90% of earthquakes. Seismic waves generated by earthquakes travel through
the Earth's interior and are measured using seismographs.
"""

DOCUMENT_CRYPTOGRAPHY = """\
# Modern Cryptography

Cryptography is the practice of securing communication in the presence of adversaries.
Modern cryptographic systems are built on mathematical problems that are computationally
hard to solve without a secret key.

## Symmetric Encryption

In symmetric encryption, the same key is used for both encryption and decryption. AES
(Advanced Encryption Standard) operates on 128-bit blocks and supports key sizes of 128,
192, and 256 bits. AES is the standard for encrypting data at rest and in transit.

## Public-Key Cryptography

Public-key cryptography uses a pair of keys: a public key for encryption and a private
key for decryption. RSA relies on the difficulty of factoring large prime numbers.
Elliptic curve cryptography (ECC) achieves equivalent security with shorter keys by
exploiting the algebraic structure of elliptic curves over finite fields.
"""


@pytest.fixture(scope="module")
def client():
    return httpx.Client(base_url=API_URL, timeout=300)


@pytest.fixture(scope="module")
def api_available(client):
    """Verify the API is reachable."""
    try:
        r = client.get("/health")
        assert r.status_code in (200, 503)
    except httpx.ConnectError:
        pytest.skip("API not reachable at localhost:8000")


def _top_doc_id(body: dict) -> str:
    """Return the document_id with the highest score from a query response."""
    docs = body["documents"]
    assert len(docs) >= 1
    return max(docs, key=lambda d: d["score"])["document_id"]


class TestMultiDocumentQuery:
    """Ingest three documents on different topics, query for each."""

    doc_ids = {}

    def test_01_ingest_three_documents(self, client, api_available):
        for name, text in [
            ("photosynthesis", DOCUMENT_PHOTOSYNTHESIS),
            ("tectonics", DOCUMENT_PLATE_TECTONICS),
            ("cryptography", DOCUMENT_CRYPTOGRAPHY),
        ]:
            r = client.post("/documents", json={"text": text})
            assert r.status_code == 200, f"Failed to ingest {name}: {r.text}"
            body = r.json()
            assert body["status"] == "complete"
            TestMultiDocumentQuery.doc_ids[name] = body["document_id"]

        r = client.get("/documents")
        assert r.status_code == 200
        assert r.json()["total"] >= 3

    def test_02_document_content_and_meta_only(self, client, api_available):
        """Default GET returns content, meta_only=true omits it."""
        doc_id = TestMultiDocumentQuery.doc_ids["photosynthesis"]

        r = client.get(f"/documents/{doc_id}")
        assert r.status_code == 200
        body = r.json()
        assert body["content"] is not None
        assert "Photosynthesis" in body["content"]

        r = client.get(f"/documents/{doc_id}", params={"meta_only": "true"})
        assert r.status_code == 200
        assert r.json()["content"] is None

    def test_03_query_ranks_photosynthesis_first(self, client, api_available):
        """Query about carbon fixation should rank the photosynthesis document first."""
        r = client.post(
            "/query",
            json={"query": "What enzyme fixes carbon dioxide in the Calvin cycle?", "token_budget": 4000},
        )
        assert r.status_code == 200
        assert _top_doc_id(r.json()) == TestMultiDocumentQuery.doc_ids["photosynthesis"]

    def test_04_query_ranks_tectonics_first(self, client, api_available):
        """Query about plate boundaries should rank the tectonics document first."""
        r = client.post(
            "/query",
            json={"query": "What happens at convergent plate boundaries?", "token_budget": 4000},
        )
        assert r.status_code == 200
        assert _top_doc_id(r.json()) == TestMultiDocumentQuery.doc_ids["tectonics"]

    def test_05_query_ranks_cryptography_first(self, client, api_available):
        """Query about encryption should rank the cryptography document first."""
        r = client.post(
            "/query",
            json={"query": "How does AES symmetric encryption work?", "token_budget": 4000},
        )
        assert r.status_code == 200
        assert _top_doc_id(r.json()) == TestMultiDocumentQuery.doc_ids["cryptography"]

    def test_06_query_ranks_tectonics_first_for_san_andreas(self, client, api_available):
        """Query about the San Andreas Fault should rank the tectonics document first."""
        r = client.post(
            "/query",
            json={"query": "Where is the San Andreas Fault?", "token_budget": 4000},
        )
        assert r.status_code == 200
        assert _top_doc_id(r.json()) == TestMultiDocumentQuery.doc_ids["tectonics"]
